[package]
name = "systemd"
version = "0.0.7"
license = "LGPL-2.1+"
description = "A rust interface to libsystemd provided APIs"
repository = "https://github.com/kteza1/asystemd.rs"

[dependencies]
log = "0.*"
libc = "0.*"

[dependencies.libsystemd-sys]
path = "libsystemd-sys"
version = "0.*"
